image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_VERSION: $CI_COMMIT_TAG

before_script:
  - "echo 构建版本号: ${IMAGE_VERSION}"
  - "echo 标签: ${CI_COMMIT_TAG}"
  - "echo 提交的标题: ${CI_COMMIT_TITLE}"

stages:
  - build
  - package

maven-build:
  image: maven:3-jdk-8
  stage: build
  tags:
    - DC8
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  tags:
    - DC8
  script:
    - docker build -t $CONTAINER_IMAGE:$IMAGE_VERSION .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker push $CONTAINER_IMAGE:$IMAGE_VERSION\
    - docker logout